function cfg = MarijnCaseCfg(cfg)

switch cfg.whattype
     case {1} % Stim + vary Wee
        cfg.plot.options{1} = 'Figure1part1';
        cfg.plot.options{2} = 'Figure1part3';
        cfg.plot.options{3} = 'Figure1part4';
        cfg.plot.options{4} = 'Figure3part1';
        cfg.plot.options{5} = 'Figure3part2';
        cfg.Nnet            = 60; % 10 uur simulation
        cfg.npara           = 51;
        cfg.patdrive        = 1;
        cfg.stimwindow      = [0 60];
        cfg.needsbasefire   = false;
        cfg.var.SynConMat   = linspace(0.015, 0.04, cfg.npara);
     case {2} % varying network size (N) and connectivity prob (p)
        cfg.plot.options{1} = 'Figure1part2';
        cfg.do.distance     = true; 
        cfg.Nt              = 1;
        cfg.Nnet            = 60; % 60 x 5 x 5 x 4 = 3 uur simulatie
        cfg.npara           = 5*5;
            varpconSyn = [0.01 0.02 0.05 0.09 0.15]; % make sure there is a 0.05 in here
            varpconSyn = repmat(varpconSyn,5,1);
        cfg.var.pconSyn     = varpconSyn(:)';
            varNe = round(logspace(log10(200),log10(1000),5));
        cfg.var.Ne          = repmat(varNe,1,5);
     case {3} % ROC vs noise
        cfg.plot.options{1} = 'Figure2part1';
        cfg.plot.options{2} = 'Figure2part2';
        cfg.plot.options{3} = 'Figure2part3';
        cfg.plot.options{4} = 'Figure2part4';
        cfg.plot.options{5} = 'Figure4part3';
        cfg.plot.times      = 6000:14000;
        cfg.do.distance     = true;
        cfg.do.kcorecentr   = true;
        cfg.Nnet            = 120; % 64 uur simulatie
        cfg.npara           = 15;
        cfg.patdrive        = 2;
        cfg.NFLEX_stim      = 4; 
        cfg.Nt              = 14000;
        cfg.var.noisehz     = 0.075:0.0025:0.0725 + 0.0025 * cfg.npara;            
     case {4} % ROC vs nstim
        cfg.plot.options{1} = 'Figure4part1';
        cfg.plot.options{2} = 'Figure4part2';
        cfg.plot.options{3} = 'Figure4part3';
        cfg.plot.times      = 5000:20000;
        cfg.Nnet            = 120; % 25 uur simulatie
        cfg.npara           = 7;
        cfg.patdrive        = 2;
        cfg.inettypes       = 1:4;
        cfg.Nt              = 20000;
        cfg.var.NFLEX_stim  = 0:cfg.npara - 1;
        cfg.only1basefire   = true;
        cfg.noisehz         = 0.098;
     case {5} % STDP forms ACOR
        cfg.plot.options{1}  ='Figure2part1';
        cfg.plot.options{2} = 'Figure6part1';
        cfg.plot.times      = 10:100000;
        cfg.dostdp          = true;
        cfg.Nnet            = 60;
        cfg.npara           = 1;
        cfg.inettypes       = 3;
        cfg.Nt              = 200000;
        cfg.stdpselect_t    = 200000;
        cfg.frtar           = 1.5;
        cfg.var.noisehz     = .1;
        cfg.pconSyn(1,1)    = 0.1;
    case {501} % STDP forms ACOR weight-dependent
        cfg.plot.options{1}  ='Figure2part1';
        cfg.plot.options{2} = 'Figure6part1';
        cfg.plot.times      = 10:50000;
        cfg.dostdp          = true;
        cfg.Nnet            = 36;
        cfg.npara           = 1;
        cfg.inettypes       = 3;
        cfg.Nt              = 1000000;
        cfg.stdpselect_t    = 1000000;
        cfg.frtar           = 1.5;
        cfg.var.noisehz     = .1;
        cfg.pconSyn(1,1)    = 0.1;
        cfg.morrisonstdp    = true;
    case {6} % ROC vs noise - pcon 10%
        cfg.plot.options{1} = 'Figure2part1';
        cfg.plot.options{2} = 'Figure2part2';
        cfg.plot.options{3} = 'Figure2part3';
        cfg.plot.options{4} = 'Figure2part4';
        cfg.plot.options{5} = 'Figure4part3';
        cfg.plot.times      = 6000:13000;
        cfg.do.distance     = true;
        cfg.do.kcorecentr   = true;
        cfg.Nnet            = 60;
        cfg.npara           = 26;
        cfg.var.noisehz     = 0.03:0.005:0.025 + 0.005 * cfg.npara;
        cfg.inettypes       = 1:2;
        cfg.patdrive        = 3;
        cfg.NFLEX_stim      = 4;
        cfg.pconSyn(1,1)    = 0.1;
        cfg.Nt              = 14000; 
    case {61} % ROC vs noise - pcon 3%
        cfg.plot.options{1} = 'Figure2part1';
        cfg.plot.options{2} = 'Figure2part2';
        cfg.plot.options{3} = 'Figure2part3';
        cfg.plot.options{4} = 'Figure2part4';
        cfg.plot.options{5} = 'Figure4part3';
        cfg.plot.times      = 6000:13000;
        cfg.do.distance     = true;
        cfg.do.kcorecentr   = true;
        cfg.Nnet            = 60;
        cfg.npara           = 26;
        cfg.var.noisehz     = 0.03:0.005:0.025 + 0.005 * cfg.npara;
        cfg.inettypes       = 1:2;
        cfg.patdrive        = 3;
        cfg.NFLEX_stim      = 4;
        cfg.pconSyn(1,1)    = 0.03;
        cfg.Nt              = 14000; 
    case {62} % ROC vs noise - pcon 1%
        cfg.plot.options{1} = 'Figure2part1';
        cfg.plot.options{2} = 'Figure2part2';
        cfg.plot.options{3} = 'Figure2part3';
        cfg.plot.options{4} = 'Figure2part4';
        cfg.plot.options{5} = 'Figure4part3';
        cfg.plot.times      = 6000:13000;
        cfg.do.distance     = true;
        cfg.do.kcorecentr   = true;
        cfg.Nnet            = 60;
        cfg.npara           = 26;
        cfg.var.noisehz     = 0.03:0.005:0.025 + 0.005 * cfg.npara;
        cfg.inettypes       = 1:2;
        cfg.patdrive        = 3;
        cfg.NFLEX_stim      = 4;
        cfg.pconSyn(1,1)    = 0.01;
        cfg.Nt              = 14000; 
    case {63} % ROC vs noise - pcon 5%
        cfg.plot.options{1} = 'Figure2part1';
        cfg.plot.options{2} = 'Figure2part2';
        cfg.plot.options{3} = 'Figure2part3';
        cfg.plot.options{4} = 'Figure2part4';
        cfg.plot.options{5} = 'Figure4part3';
        cfg.plot.times      = 6000:13000;
        cfg.do.distance     = true;
        cfg.do.kcorecentr   = true;
        cfg.Nnet            = 60;
        cfg.npara           = 26;
        cfg.var.noisehz     = 0.03:0.005:0.025 + 0.005 * cfg.npara;
        cfg.inettypes       = 1:2;
        cfg.patdrive        = 3;
        cfg.NFLEX_stim      = 4;
        cfg.pconSyn(1,1)    = 0.05;
        cfg.Nt              = 14000;
     case {7} % ROC vs noise - N = 300
        cfg.plot.options{1} = 'Figure2part1';
        cfg.plot.options{2} = 'Figure2part2';
        cfg.plot.options{3} = 'Figure2part3';
        cfg.plot.options{4} = 'Figure2part4';
        cfg.plot.options{5} = 'Figure4part3';
        cfg.plot.times      = 6000:13000;
        cfg.do.distance     = true;
        cfg.do.kcorecentr   = true;
        cfg.Nnet            = 60;
        cfg.npara           = 24; % was 40 at 0.005
        cfg.var.noisehz     = 0.03:0.0075:0.0225 + 0.0075 * cfg.npara;
        cfg.inettypes       = 1:2;
        cfg.patdrive        = 3;
        cfg.NFLEX_stim      = 4;
        cfg.Ne              = 240;
        cfg.Nt              = 14000; 
        cfg.vary_spike_with_inet = 6;
    case {71} % ROC vs noise - N = 600
        cfg.plot.options{1} = 'Figure2part1';
        cfg.plot.options{2} = 'Figure2part2';
        cfg.plot.options{3} = 'Figure2part3';
        cfg.plot.options{4} = 'Figure2part4';
        cfg.plot.options{5} = 'Figure4part3';
        cfg.plot.times      = 6000:13000;
        cfg.do.distance     = true;
        cfg.do.kcorecentr   = true;
        cfg.Nnet            = 60;
        cfg.npara           = 24; %was 30 at 0.01
        cfg.var.noisehz     = 0.03:0.004:0.026 + 0.004 * cfg.npara;
        cfg.inettypes       = 1:2;
        cfg.patdrive        = 3;
        cfg.NFLEX_stim      = 4;
        cfg.Ne              = 480;
        cfg.Nt              = 14000; 
        cfg.vary_spike_with_inet = 6;
    case {72} % size 
        cfg.plot.options{1} = 'Figure2part1';
        cfg.plot.options{2} = 'Figure2part2';
        cfg.plot.options{3} = 'Figure2part3';
        cfg.plot.options{4} = 'Figure2part4';
        cfg.plot.options{5} = 'Figure4part3';
        cfg.plot.times      = 6000:13000;
        cfg.do.distance     = true;
        cfg.do.kcorecentr   = true;
        cfg.Nnet            = 60; %5 days
        cfg.npara           = 24;
        cfg.var.noisehz     = 0.03:0.0025:0.0275 + 0.0025 * cfg.npara;
        cfg.inettypes       = 1:2;
        cfg.patdrive        = 3;
        cfg.NFLEX_stim      = 4;
        cfg.Ne              = 960;
        cfg.Nt              = 14000;
end
